# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import chat_pb2 as proto_dot_chat__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/chat_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChatServiceStub(object):
    """Chat service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ChatStream = channel.stream_stream(
                '/chat.ChatService/ChatStream',
                request_serializer=proto_dot_chat__pb2.ChatMessage.SerializeToString,
                response_deserializer=proto_dot_chat__pb2.ChatMessage.FromString,
                _registered_method=True)
        self.JoinChat = channel.unary_unary(
                '/chat.ChatService/JoinChat',
                request_serializer=proto_dot_chat__pb2.User.SerializeToString,
                response_deserializer=proto_dot_chat__pb2.JoinResponse.FromString,
                _registered_method=True)
        self.SendMessages = channel.stream_unary(
                '/chat.ChatService/SendMessages',
                request_serializer=proto_dot_chat__pb2.ChatMessage.SerializeToString,
                response_deserializer=proto_dot_chat__pb2.MessageResponse.FromString,
                _registered_method=True)
        self.GetChatHistory = channel.unary_stream(
                '/chat.ChatService/GetChatHistory',
                request_serializer=proto_dot_chat__pb2.HistoryRequest.SerializeToString,
                response_deserializer=proto_dot_chat__pb2.ChatMessage.FromString,
                _registered_method=True)


class ChatServiceServicer(object):
    """Chat service definition
    """

    def ChatStream(self, request_iterator, context):
        """Send message stream between users
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JoinChat(self, request, context):
        """Join the chat room
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessages(self, request_iterator, context):
        """Client streaming: Send multiple messages and get a summary response
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChatHistory(self, request, context):
        """Server streaming: Get chat history or announcements
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ChatStream': grpc.stream_stream_rpc_method_handler(
                    servicer.ChatStream,
                    request_deserializer=proto_dot_chat__pb2.ChatMessage.FromString,
                    response_serializer=proto_dot_chat__pb2.ChatMessage.SerializeToString,
            ),
            'JoinChat': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinChat,
                    request_deserializer=proto_dot_chat__pb2.User.FromString,
                    response_serializer=proto_dot_chat__pb2.JoinResponse.SerializeToString,
            ),
            'SendMessages': grpc.stream_unary_rpc_method_handler(
                    servicer.SendMessages,
                    request_deserializer=proto_dot_chat__pb2.ChatMessage.FromString,
                    response_serializer=proto_dot_chat__pb2.MessageResponse.SerializeToString,
            ),
            'GetChatHistory': grpc.unary_stream_rpc_method_handler(
                    servicer.GetChatHistory,
                    request_deserializer=proto_dot_chat__pb2.HistoryRequest.FromString,
                    response_serializer=proto_dot_chat__pb2.ChatMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chat.ChatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chat.ChatService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChatService(object):
    """Chat service definition
    """

    @staticmethod
    def ChatStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/chat.ChatService/ChatStream',
            proto_dot_chat__pb2.ChatMessage.SerializeToString,
            proto_dot_chat__pb2.ChatMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def JoinChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.ChatService/JoinChat',
            proto_dot_chat__pb2.User.SerializeToString,
            proto_dot_chat__pb2.JoinResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendMessages(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/chat.ChatService/SendMessages',
            proto_dot_chat__pb2.ChatMessage.SerializeToString,
            proto_dot_chat__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChatHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/chat.ChatService/GetChatHistory',
            proto_dot_chat__pb2.HistoryRequest.SerializeToString,
            proto_dot_chat__pb2.ChatMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
